apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30   # 30 secs pause
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
          ports:
            - containerPort: 80

# it is a ReplicaSets with one additional feature ( automatic rolling updates with zero downtime)
# you can rollback if something goes wrong
#Group: app, Version: v1, Kind: Deployment

# Rolling updates: kubectl rollout status deploy webapp  -->
# REVISION 2 - is the one we had before
# REVISION 3 - Current live

# REVISION 3 - 
# REVISION 4 - after the rollback we are now on REVISION 4 retun of what we had in REVISION 2


# To return back to REVISION 2 - kubectl rollout undo deploy webapp --to-revision=2