# ReplicaSet: Extra piece of configurations that we give to kubernetes
# How many instances of this pod do we want kubernetes to make sure 
# are  runniung at any one time

apiVersion: apps/v1  #tag version based on api ( can be in development)
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
          ports:
            - containerPort: 80


# CURRENT: is the number of containers that are running
# READY: is the number of container that are responding to requests
# if we had more than 1 replicas,( like 2) then even if one pod crashes it will still be vailable to service request