apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  containers:
    - name: fleetman-queue
      image: richardchesterwood/k8s-fleetman-queue:release1
      ports:
        - containerPort: 8161

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-service
spec:
  selector:
    app: fleetman-queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  type: NodePort